/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118369-g959b799c8d-20250127"
#endif /* AVUTIL_FFVERSION_H */
